paths:
  models:
    pose_landmarker: models/pose_landmarker_heavy.task
    object_detector: models/object_detector_lite0.tflite
  data:
    input_images: data/input/images
    input_videos: data/input/videos
    output: data/output
    landmarks: data/landmarks
    gaze_folder: data/input/gaze

settings:
  video_input_extension: "*.avi"
  video_output_extension: "mp4v"
  alpha: 0.7
  num_poses: 2
  segmentation_threshold: 0.5
  max_results: 10
  score_threshold: 0.2
  max_head_radius: 120
  min_head_radius: 110
  max_arm_thickness: 80
  min_arm_thickness: 75
  max_hand_radius: 65
  min_hand_radius: 55
  mask_dilation_kernel: 21  # pixels to expand beyond body border, must be odd
  reference_video: "AM_A7_S4_B6_GM_D1_F1"
  head_dilation: 0.75
  hand_dilation: 2.0
  arm_dilation: 0.45
  activity_dilation: 1.0
  seg_video_alpha: 0.0

pose_landmarks:
  - NOSE
  - LEFT_EYE_INNER
  - LEFT_EYE
  - LEFT_EYE_OUTER
  - RIGHT_EYE_INNER
  - RIGHT_EYE
  - RIGHT_EYE_OUTER
  - LEFT_EAR
  - RIGHT_EAR
  - MOUTH_LEFT
  - MOUTH_RIGHT
  - LEFT_SHOULDER
  - RIGHT_SHOULDER
  - LEFT_ELBOW
  - RIGHT_ELBOW
  - LEFT_WRIST
  - RIGHT_WRIST
  - LEFT_PINKY
  - RIGHT_PINKY
  - LEFT_INDEX
  - RIGHT_INDEX
  - LEFT_THUMB
  - RIGHT_THUMB
  - LEFT_HIP
  - RIGHT_HIP
  - LEFT_KNEE
  - RIGHT_KNEE
  - LEFT_ANKLE
  - RIGHT_ANKLE
  - LEFT_HEEL
  - RIGHT_HEEL
  - LEFT_FOOT_INDEX
  - RIGHT_FOOT_INDEX