paths:
  models:
    pose_landmarker: models/pose_landmarker_heavy.task
  data:
    input_images: data/input/images
    input_videos: data/input/videos
    output: data/output

settings:
  video_input_extension: "*.avi"
  video_output_extension: "*.mp4"